winget uninstall "Copilot"
winget uninstall "Game Bar"
winget uninstall "Game Speech Window"
winget uninstall "Microsoft 365"
winget uninstall "Microsoft Bing Search"
winget uninstall "Microsoft Clipchamp"
winget uninstall "Microsoft News"
winget uninstall "Microsoft Sticky Notes"
winget uninstall "MSN Weather"
winget uninstall "Outlook for Windows"
winget uninstall "Power Automate"
winget uninstall "Quick Assist"
winget uninstall "Snipping Tool"
winget uninstall "Solitaire & Casual Games"
winget uninstall "Windows Clock"
winget uninstall "Xbox"
winget uninstall "Xbox Identity Provider"
winget uninstall "Xbox TCUI"
